name: Run Tests

on:
  pull_request:
    types:
      - opened
      - synchronized

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 12

      - name: Build and Test
        run: kotlin -classpath src tests.testdatastructures.TestLinkedListKt